name: Docker Image CI for GHCR

on: push

jobs:
  build and publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username nandhag29 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/nandhag29/arithmetic-service:latest --file Dockerfile .
          docker push ghcr.io/nandhag29/arithmetic-service:latest
